### PR TITLE
Build process improvements

### PR DESCRIPTION
**Pull request by rosterpugilistcostume**

### CODE REVIEW

**Review by mlee-asana — APPROVED** [review]
not 100% sure what all of these changes do, but AFAICT it's all build (not user-facing) changes so probably safe!

you may already be tracking this/doing as a followup, but would also be nice to update the README to reflect these changes

**Comment by jv-asana** [comment]
> not 100% sure what all of these changes do, but AFAICT it's all build (not user-facing) changes so probably safe!
> 
> you may already be tracking this/doing as a followup, but would also be nice to update the README to reflect these changes

+1 for README update

**Comment by jv-asana** [comment]
@rosterpugilistcostume What are all these removals? I can't seem to find some of these files on the master branch.

I am confident with the docs_build part since we've compared this with the old method and partially the first time setup part but have we tested?

- [ ] Client library PR generation
- [ ] API Explorer commands

**Review by jv-asana — APPROVED** [review]
Thanks for explaining about the `node_modules/yaml removal` and confirming that setup and API Explorer works. Let's go ahead and merge this.

We'll need to make sure to add back the client library gen code later. Will also try debugging later on my end to get this to work on my computer.

**Pull request merged**
