### PR TITLE
Update Makefile commands. Rename UI Components to App Components.

### PR DESCRIPTION
**Pull request by aw-asana**

### CODE REVIEW

**Comment by aw-asana** [comment]
`ui_hooks_oas.yaml` will be updated separately.

@rossgrambo -- do dot files (`source/templates/main.dot`, `source/templates/operation.dot`) need to be updated manually as well? There are references to "UI Components" in those. If so, I can push another update to this PR.

**Review by rossgrambo — APPROVED** [review]
> @rossgrambo -- do dot files (source/templates/main.dot, source/templates/operation.dot) need to be updated manually as well? There are references to "UI Components" in those. If so, I can push another update to this PR.

Yes, you'll need to update those as well. Those are what widdershins uses.

As long as you served and nothing seemed broken, this LGTM! :D

**Comment by aw-asana** [comment]
@rossgrambo Sounds good! If things look good in the newly-pushed commit (i.e., the one with `.dot` files), I'll go ahead and merge it.

**Comment by rossgrambo** [comment]
LGTM!

**Pull request merged**
