### PR TITLE
Remove Beta Tag from Docs

### PR DESCRIPTION
**Pull request by atair-lgtm**

### CODE REVIEW

**Comment by atair-lgtm** [comment]
image

**Comment by rossgrambo** [comment]
Hmm I think we should center the "Send Feedback" button if BETA is missing.

**Comment by atair-lgtm** [comment]
Yeah initially it was centered and then I moved it because I felt like it drew too much attention to it.

**Comment by atair-lgtm** [comment]
This is what it looks like centered 
image

**Comment by atair-lgtm** [comment]
Going to keep it as aligned left for now.

**Pull request merged**
